assets: /inspire/hdd/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/third_party/LIBERO/libero/libero/assets
bddl_files: /inspire/hdd/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/third_party/LIBERO/libero/libero/bddl_files
benchmark_root: /inspire/hdd/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/third_party/LIBERO/libero/libero
datasets: /inspire/hdd/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/third_party/LIBERO/libero/datasets
init_states: /inspire/hdd/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/third_party/LIBERO/libero/libero/init_files
