name: libero90

task_name: libero90

shape_meta: &shape_meta
  obs:
    robot0_eef_pos:
      shape: [3]
      type: state
    robot0_eef_quat:
      shape: [4]
      type: state
    robot0_gripper_qpos:
      shape: [2]
      type: state
    task_uid:
      shape: [1]
      type: state
  action:
    shape: [7]


dataset:
  _target_: oat.dataset.zarr_dataset.ZarrDataset
  zarr_path: data/libero/libero90_N${training.num_demo}.zarr
  obs_keys:
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - task_uid
  action_key: action
  n_obs_steps: 1
  n_action_steps: ${horizon}
  seed: ${seed}
  val_ratio: 0.1
