# @package _global_

defaults:
  - override /data: libero_streaming_episode_2cam
  - override /model: fastwam_streaming
  - _self_

batch_size: 96
num_workers: 8
dataloader_disable_shared_memory: false
dataloader_pin_memory: false
dataloader_persistent_workers: false
dataloader_prefetch_factor: null

model:
  mot_checkpoint_mixed_attn: false
  streaming:
    freeze_video_expert: true
    obs_stride: ${STREAMING.obs_stride}
    streaming_train:
      enabled: true
      cache_mode: full_cur
      token_noise_pattern: front_low_high

lr_scheduler_type: "cosine"
learning_rate: 5e-5
num_epochs: 200
max_steps: null
log_every: 10
save_every: 500
eval_every: 125

gradient_accumulation_steps: 1
weight_decay: 1e-2
resume: null

wandb:
  enabled: true
  project: fast-wam
  name: libero_streaming_action_ft_2cam224_5e-5
  group: libero_streaming
  mode: offline
