model:
  vla_config_path: configs/vla_qwen3_rtc.yaml

rtc_async:
  config_path: configs/rtc_async_vla.yaml
  train_vla: true
  use_attention_mask: true

dataset:
  zarr_path: /inspire/qb-ilm/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/streaming_vla/oat/data/libero_256/libero90_N4500.zarr
  image_key: agentview_rgb
  aux_image_key: robot0_eye_in_hand_rgb
  action_key: action
  prompt_key: prompt
  state_keys:
    - robot0_joint_pos
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
  anchor_stride_steps: 4
  episode_cache_size: 8
  max_episodes: null
  val_ratio: 0.1

training:
  seed: 42
  num_epochs: 30
  max_grad_norm: 1.0
  source_dt_ms: 10
  step_dt_min_ms: 160
  step_dt_max_ms: 220
  mixed_precision: "no"
  allow_tf32: true
  cudnn_benchmark: true
  float32_matmul_precision: high
  max_train_batches: null

optimizer:
  action_expert_lr: 5.0e-5
  vla_lr: 5.0e-6
  beta1: 0.9
  beta2: 0.95
  weight_decay: 0.0

scheduler:
  name: cosine
  warmup_steps: 500

dataloader:
  batch_size: 15
  shuffle: true
  num_workers: 5
  pin_memory: true
  persistent_workers: true
  drop_last: false

val_dataloader:
  batch_size: 15
  shuffle: true
  num_workers: 5
  pin_memory: true
  persistent_workers: true
  drop_last: false

eval:
  every_epochs: 1
  max_val_batches: null
  denoise_mse_num_samples: 64

checkpoint:
  save_every: 2
  best_monitor: val/rtc_loss
  best_mode: min
  resume_from: "/inspire/qb-ilm/project/robot-reasoning/xiangyushun-p-xiangyushun/luye/Streaming_VLA/checkpoints/epoch_0000.pt"
